import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  infrastructureSidebar: [{ type: 'autogenerated', dirName: 'infrastructure' }],
  hostServicesSidebar: [{ type: 'autogenerated', dirName: 'host-services' }],
  hostMatchServersSidebar: [{ type: 'autogenerated', dirName: 'host-match-servers' }],
};

export default sidebars;
