import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  infrastructureSidebar: [{ type: 'autogenerated', dirName: '001-infrastructure' }],
  servicesSidebar: [{ type: 'autogenerated', dirName: '002-services' }],
  utilitiesSidebar: [{ type: 'autogenerated', dirName: '003-utilities' }],
};

export default sidebars;
